Repository validator-labs/validator-plugin-vsphere, pull requests merged in 2024-08, with the labels that each got.

#316 chore: remove unused helm value
  chart/validator-plugin-vsphere/README.md
  chart/validator-plugin-vsphere/templates/_helpers.tpl
  chart/validator-plugin-vsphere/templates/deployment.yaml
  chart/validator-plugin-vsphere/values.yaml
Labels: size:S

#318 refactor: support direct rule evaluation
  api/v1alpha1/vspherevalidator_types.go
  go.mod
  go.sum
  internal/controller/vspherevalidator_controller.go
  internal/controller/vspherevalidator_controller_test.go
  pkg/constants/constants.go
  pkg/validate/validate.go
  pkg/validators/computeresources/computeresources.go
  pkg/validators/computeresources/computeresources_test.go
  pkg/validators/ntp/ntp.go
  pkg/validators/privileges/common.go
  pkg/validators/privileges/entity_privilege.go
  pkg/validators/privileges/entity_privilege_test.go
  pkg/validators/privileges/role_privilege_test.go
  pkg/validators/privileges/role_privileges.go
  pkg/validators/tags/tags.go
  pkg/vcsim/vcsim.go
  pkg/vsphere/resource_pool.go
  tests/integration/tags/tags.go
Labels: enhancement, size:L

#311 chore(main): release 0.0.29
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-vsphere/Chart.yaml
  chart/validator-plugin-vsphere/README.md
  chart/validator-plugin-vsphere/values.yaml
Labels: autorelease: pending, size:S

#323 chore: satisfy ValidationRule
  api/v1alpha1/vspherevalidator_types.go
  go.mod
  go.sum
Labels: size:XS

#320 chore(main): release 0.0.30
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-vsphere/Chart.yaml
  chart/validator-plugin-vsphere/README.md
  chart/validator-plugin-vsphere/values.yaml
Labels: autorelease: pending, size:S, lgtm

#336 fix: deduplicate resource rule scope to prevent resource overflow
  Dockerfile.devspace
  README.md
  pkg/validate/validate.go
  pkg/validators/computeresources/computeresources.go
  pkg/validators/computeresources/computeresources_test.go
Labels: bug, size:L, lgtm

#338 feat: support inline auth for vCenter
  api/v1alpha1/vspherevalidator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  chart/validator-plugin-vsphere/crds/validation.spectrocloud.labs_vspherevalidators.yaml
  config/crd/bases/validation.spectrocloud.labs_vspherevalidators.yaml
  config/samples/vsphere-validator-compute.yaml
  config/samples/vsphere-validator-entity-privilege.yaml
  config/samples/vsphere-validator-explicit-auth.yaml
  config/samples/vsphere-validator-ntp.yaml
  config/samples/vsphere-validator-role-privilege.yaml
  config/samples/vsphere-validator-tag.yaml
  config/samples/vsphere-validator.yaml
  internal/controller/vspherevalidator_controller.go
Labels: size:L, lgtm, new-feature

#328 chore(main): release 0.0.31
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-vsphere/Chart.yaml
  chart/validator-plugin-vsphere/README.md
  chart/validator-plugin-vsphere/values.yaml
Labels: autorelease: pending, size:M, lgtm

#341 refactor: make each rule implement `validationrule.Interface`
  api/v1alpha1/vspherevalidator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  chart/validator-plugin-vsphere/crds/validation.spectrocloud.labs_vspherevalidators.yaml
  config/crd/bases/validation.spectrocloud.labs_vspherevalidators.yaml
  go.mod
  go.sum
  internal/controller/vspherevalidator_controller_test.go
  pkg/validators/computeresources/computeresources_test.go
  pkg/validators/ntp/ntp.go
  pkg/validators/privileges/entity_privilege_test.go
  pkg/validators/privileges/role_privileges.go
  tests/integration/tags/tags.go
Labels: enhancement, size:L, lgtm

#343 chore(main): release 0.0.32
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-vsphere/Chart.yaml
  chart/validator-plugin-vsphere/README.md
  chart/validator-plugin-vsphere/values.yaml
Labels: autorelease: pending, size:S

#346 fix: embedding structs related to `validationrule.Interface`
  api/v1alpha1/vspherevalidator_types.go
Labels: bug, size:S

#344 chore: assert that PluginSpec is implemented
  api/v1alpha1/vspherevalidator_types.go
  go.mod
  go.sum
Labels: size:XS, lgtm

#348 chore(main): release 0.0.33
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-vsphere/Chart.yaml
  chart/validator-plugin-vsphere/README.md
  chart/validator-plugin-vsphere/values.yaml
Labels: bug, autorelease: pending, size:S

#351 fix: YAML rendering of structs embedded in rules
  api/v1alpha1/vspherevalidator_types.go
Labels: bug, size:S

#349 chore(main): release 0.0.34
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-vsphere/Chart.yaml
  chart/validator-plugin-vsphere/README.md
  chart/validator-plugin-vsphere/values.yaml
Labels: autorelease: pending, size:S
