Repository validator-labs/validator-plugin-vsphere, pull requests merged in 2024-07, with the labels that each got.

#286 chore(main): release 0.0.27
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-vsphere/Chart.yaml
  chart/validator-plugin-vsphere/README.md
  chart/validator-plugin-vsphere/values.yaml
Labels: autorelease: pending, size:M

#309 ci: add reviewable-ext make target to update chart crds
  Makefile
  chart/validator-plugin-vsphere/crds/validation.spectrocloud.labs_vspherevalidators.yaml
Labels: enhancement, size:M, lgtm

#299 chore(main): release 0.0.28
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-vsphere/Chart.yaml
  chart/validator-plugin-vsphere/README.md
  chart/validator-plugin-vsphere/values.yaml
Labels: autorelease: pending, size:S
