Repository validator-labs/validator-plugin-vsphere, pull requests merged in 2024-12, with the labels that each got.

#417 chore: re-scaffold project
  .golangci.yml
  api/v1alpha1/vspherevalidator_types.go
  chart/validator-plugin-vsphere/README.md
  chart/validator-plugin-vsphere/templates/deployment.yaml
  chart/validator-plugin-vsphere/templates/metrics-auth-rbac.yaml
  chart/validator-plugin-vsphere/templates/metrics-reader-rbac.yaml
  chart/validator-plugin-vsphere/templates/metrics-service.yaml
  chart/validator-plugin-vsphere/values.yaml
  cmd/main.go
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/default/manager_metrics_patch.yaml
  config/default/metrics_service.yaml
  config/manager/manager.yaml
  config/network-policy/allow-metrics-traffic.yaml
  config/network-policy/kustomization.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/kustomization.yaml
  config/rbac/metrics_auth_role.yaml
  config/rbac/metrics_auth_role_binding.yaml
  config/rbac/metrics_reader_role.yaml
  config/samples/kustomization.yaml
  go.mod
  go.sum
  internal/controller/suite_test.go
  internal/controller/vspherevalidator_controller.go
  internal/controller/vspherevalidator_controller_test.go
  pkg/vsphere/user.go
  pkg/vsphere/vsphere.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/e2e_test.go
  tests/utils/e2e/e2e_utils.go
Labels: enhancement, size:XL

#380 chore(main): release 0.1.5
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-vsphere/Chart.yaml
  chart/validator-plugin-vsphere/README.md
  chart/validator-plugin-vsphere/values.yaml
Labels: autorelease: pending, size:M, lgtm

#424 chore(main): release 0.1.6
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-vsphere/Chart.yaml
  chart/validator-plugin-vsphere/README.md
  chart/validator-plugin-vsphere/values.yaml
Labels: autorelease: pending, size:S
